[build]
rustflags = ["-C", "opt-level=3"]

[alias]
rr = "run --release --"
ig = "run --release -- 1000 -o images/ig.png"

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/bin/x86_64-w64-mingw32-ar"

