[build]
rustflags = ["-C", "opt-level=3"]

[alias]
rd =  "run -- -s config/basic_scene.ini -O config/basic_observer.ini"

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/bin/x86_64-w64-mingw32-ar"
